definitions:
  model.HealthResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthResponse'
      summary: Show the status of server.
swagger: "2.0"
